#!/bin/bash

add_ppas () {
  sudo add-apt-repository ppa:neovim-ppa/stable
  echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823

  # Signal
  curl -s https://updates.signal.org/desktop/apt/keys.asc | sudo apt-key add -
  echo "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" | sudo tee -a /etc/apt/sources.list.d/signal-xenial.list

  sudo apt-get update
}

install_stuff () {
  sudo apt-get install -y \
    powertop \
    xbacklight \
    xautolock \
    compton \
    i3 \
    display-dhammapada \
    curl \
    ctags \
    git \
    neovim \
    mutt \
    pandoc \
    w3m w3m-img \
    signal-desktop \
    xclip \
    source-highlight
}

update_alternatives () {
  sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
  sudo update-alternatives --config vi
  sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
  sudo update-alternatives --config vim
  sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
  sudo update-alternatives --config editor
}

install_vim_files () {
  mkdir repos
  git clone https://github.com/pthorin/vim.git "$HOME"/repos/vim
  pushd "$HOME/repos/vim" || return
  if ! [ -d "$HOME/.config/nvim" ]; then mkdir -p "$HOME/.config/nvim" ; fi
  sh ./install.sh
  popd
}

install_configs () {
  declare configs=(compton dunst fish i3 i3status)
  for x in ${configs[*]} ; do
    ln -s "$(pwd)/$x" "$HOME/.config/${x}"
  done
}

install_scripts () {
  ln -s "$(pwd)/scripts" "$HOME/scripts"
}


