#!/bin/bash
MAX=$(cat /sys/class/backlight/intel_backlight/max_brightness)
CURRENT=$(cat /sys/class/backlight/intel_backlight/brightness)

function ProgressBar {
# Process data
    let _progress=(${1}*100/${2}*100)/100
    let _done=(${_progress}*1+1)/10
    let _left=10-$_done
# Build progressbar string lengths
    _fill=$(printf "%${_done}s")
    _empty=$(printf "%${_left}s")

# 1.2 Build progressbar strings and print the ProgressBar line
# 1.2.1 Output example:
# 1.2.1.1 Progress : [########################################] 100%
printf "Brightness ▃${_fill// /▅}${_empty// /▁} ${_progress}%%"

}

ProgressBar $CURRENT $MAX |tee /tmp/brightness
