#!/usr/bin/env zsh
compton --config $HOME/.config/compton/compton.conf -b &
transset --name i3bar &
noisetorch -s alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__source -i alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__source -o alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink
$HOME/.fehbg &
nm-applet &
setxkbmap -option caps:escape &
numlockx &
xmodmap ~/.Xmodmap &
slack &
teams &
signal-desktop &
dunst &
workrave &
blueman-manager &
