#!/usr/bin/env zsh
#compton --config $HOME/.config/compton/compton.conf -b -i 0.75 &
#transset --name i3bar &
dbus-update-activation-environment --all &
lxpolkit &
/usr/bin/gnome-keyring-daemon --start --components=ssh,secrets,pkcs11 &
#/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
systemctl start --user TokenUpdater.service
$HOME/.fehbg &
nm-applet &
setxkbmap -option caps:escape &
numlockx &
xmodmap ~/.Xmodmap &
slack &
signal-desktop --no-sandbox --password-store="gnome-libsecret" &
#sudo openvpn --config ~/ovpn/PTHORIN@vpn.oss.volvoc3.com.ovpn --daemon &
sudo openvpn --config ~/ovpn/PTHORIN_2026-11-18@vpn.oss.volvoc3.com.ovpn --daemon --writepid /run/openvpn/oss.pid &
dunst &
#cd ~/thirdparty-repos/Rofication/ && ./rofication-daemon.py &
workrave &
blueman-applet &
#gnome-pomodoro &
pasystray &
performance &
