#!/usr/bin/env zsh
export XDG_CURRENT_DESKTOP=sway
#compton --config $HOME/.config/compton/compton.conf -b -i 0.75 &
#transset --name i3bar &
lxpolkit &
#/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
$HOME/.fehbg &
nm-applet &
setxkbmap -option caps:escape &
numlockx &
xmodmap ~/.Xmodmap &
slack &
signal-desktop --no-sandbox --password-store="gnome-libsecret" &
sudo openvpn --config ~/ovpn/PTHORIN@vpn.oss.volvoc3.com.ovpn --daemon &
mako &
workrave &
blueman-applet &
#gnome-pomodoro &
pasystray &
