#!/bin/sh

if [ "$(xrandr | ag 'DP-6 connected' | wc -l)" -gt 0 ]; then
  xrandr --output DP-6 --auto
fi
if [ "$(xrandr |ag 'DP-4 connected' | wc -l)" -gt 0 ]; then
  xrandr --output DP-4 --auto --above DP-6 --primary
fi
"$HOME/.fehbg"

