#!/bin/sh

xrandr --auto
xrandr --output eDP-1 --auto --scale 2
xrandr --output HDMI-1 --scale 2
# internal="eDP-1"
# if [ "$(xrandr | ag "$internal connected" | wc -l)" -gt 0 ]; then
#   xrandr --output $internal --auto --scale 1.5
# fi
# if [ "$(xrandr |ag 'DP-3 connected' | wc -l)" -gt 0 ]; then
#   xrandr --output DP-3 --auto --above $internal --primary
# fi
"$HOME/.fehbg"

