# load profiler
#zmodload zsh/zprof
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:/usr/local/go/bin:/home/pthorin/.local/share/gem/ruby/3.0.0/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="agnoster"
ZSH_THEME="af-magic"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(
  #git
  #kube-ps1
  ssh-agent
  zsh-completions
  zsh-autosuggestions
  )

zstyle :omz:plugins:ssh-agent identities id_ed25519 id_rsa

source $ZSH/oh-my-zsh.sh
autoload -U compinit && compinit
compdef kubecolor=kubectl

# RIPGREP config ripgrep
RIPGREP_CONFIG_PATH=/home/pthorin/.config/ripgrep

# User configuration
export DEFAULT_USER=pthorin
prompt_context(){}
#PROMPT=$PROMPT'$(kube_ps1) '
#
# Set some paths
export PATH=$PATH:~/scripts
export PATH=$PATH:~/.local/bin
export PATH=$PATH:~/go/bin
export PATH=$PATH:~/.gem/ruby/2.7.0/bin
#export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"
# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
#export PATH=$PATH:./node_modules/.bin
export PATH=$PATH:~/repos/docker-bin
export PATH=$PATH:/usr/local/bin/kui
export PATH=$PATH:~/.cargo/bin

if (( ! ${fpath[(I)/usr/local/share/zsh/site-functions]} )); then
  FPATH=/usr/local/share/zsh/site-functions:$FPATH
fi


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export EDITOR='vim'
export PAGER='less -F'

# starship.rs
source <("starship" init zsh --print-full-init)

# copied from zsh-completion
# source $HOME/repos/dotfiles/zsh/completion.zsh
# end of copy
#bindkey -M menuselect '^[[Z' reverse-menu-complete # shift-tab reverses autocomplete

source /etc/bash_completion.d/azure-cli

#source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept
bindkey '\e' autosuggest-clear


GCM_CREDENTIAL_STORE=secretservice
# get all the zecrets!
source ~/.zecrets > /dev/null


export CODE_PATH=~/repos
export CDPATH=.:~:~/repos:~/repos/3pdx:~/repos/connected-vehicle/:~/repos/extended-vehicle:~/energy:~/repos/ash:~/repos/azure:~/repos/gitlab

# Tiny Care Terminal
#export TTC_BOTS='honest_update,dmofengineering,selfcare_bot'
export TTC_SAY_BOX='$HOME/repos/dotfiles/nyan.ansi'
export TTC_REPOS='$HOME/repos'
export TTC_REPOS_DEPTH=2
export TTC_WEATHER='Gothenburg'
export TTC_CELSIUS=true
export TTC_APIKEYS=false
export TTC_UPDATE_INTERVAL=20
export TTC_TERMINAL_TITLE=false
export TTC_POMODORO=25
export TTC_BREAK=10


# eval $(lesspipe)
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=" -R -i -J "


# Load aliases
source ~/repos/dotfiles/zsh/aliases
source ~/repos/volvoalias/azure
source ~/repos/volvoalias/gh
# Load functions
source ~/repos/dotfiles/zsh/functions
source ~/repos/dotfiles/zsh/gh_functions
# Load mob settings
source ~/repos/dotfiles/zsh/mob
function aws() {
  unset -f aws
  if [ $commands[aws] ]; then
    # aws complete
    complete -C '$(which aws_completer)' aws
  fi
  aws $*
}
# spl complete
function spl() {
  unset -f spl
  source <(spl completion zsh)
  spl $*
}
# stern complete
function stern() {
  unset -f stern
  source <(stern --completion zsh)
  stern $*
}

# gh complete
if [[ ! -d "$ZSH/completions" || ! -f "$ZSH/completions/_gh" ]]; then
    mkdir -pv $ZSH/completions
    gh completion --shell zsh > $ZSH/completions/_gh
    echo "gh added completions: gh completion --shell zsh > $ZSH/completions/_gh"
fi

if [[ ! -d "$ZSH/completions" || ! -f "$ZSH/completions/_glab" ]]; then
    mkdir -pv $ZSH/completions
    glab completion -s zsh > $ZSH/completions/_glab
    echo "glab added completions: glab completion -s zsh > $ZSH/completions/_glab"
fi

if [[ ! -d "$ZSH/completions" || ! -f "$ZSH/completions/_ctp" ]]; then
    mkdir -pv $ZSH/completions
    ctp completion zsh > $ZSH/completions/_ctp
    echo "ctp added completions: ctp completion zsh > $ZSH/completions/_ctp"
fi

if [[ ! -d "$ZSH/completions" || ! -f "$ZSH/completions/_yq" ]]; then
    mkdir -pv $ZSH/completions
    yq shell-completion zsh > $ZSH/completions/_yq
    echo "yq added completions: yq shell-completion zsh > $ZSH/completions/_yq"
fi

# sdk complete
function sdk() {
  unset -f sdk
  source <(sdk --completion bash)
  sdk $*
}

if [[ ! -d "$ZSH/completions" || ! -f "$ZSH/completions/_vacuum" ]]; then
    mkdir -pv $ZSH/completions
    vacuum completion zsh > $ZSH/completions/_vacuum
    echo "vacuum added completions: vacuum completion zsh > $ZSH/completions/_vacuum"
fi

if [[ ! -d "$ZSH/completions" || ! -f "$ZSH/completions/_k9s" ]]; then
    mkdir -pv $ZSH/completions
    k9s completion zsh > $ZSH/completions/_k9s
    echo "k9s added completions: k9s completion zsh > $ZSH/completions/_k9s"
fi

setopt nobanghist # disable history expansion
unsetopt auto_cd
# run profiler
#zprof
# direnv
eval "$(direnv hook zsh)"

# HELP!
export HELPDIR='/usr/share/zsh/help'
alias help='run-help'

eval "$(op completion zsh)"; compdef _op op

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

if [ -x $(which lolcat) ] && [ -x $(which fortune) ]; then
  fortune ~/repos/dotfiles/breathe |lolcat
fi

# REVIEW_BASE for git review and git reviewone
REVIEW_BASE=main


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"

[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"




